/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    Bottom: typeof import('./components/Bottom.vue')['default']
    BurgerClosedIcon: typeof import('./components/icons/BurgerClosedIcon.vue')['default']
    BurgerOpenIcon: typeof import('./components/icons/BurgerOpenIcon.vue')['default']
    Companies: typeof import('./components/Companies.vue')['default']
    ContainerIcon: typeof import('./components/icons/ContainerIcon.vue')['default']
    DarkModeIcon: typeof import('./components/icons/DarkModeIcon.vue')['default']
    Gameoflife: typeof import('./components/playground/GameOfLife.vue')['default']
    GameOfLife: typeof import('./components/playground/GameOfLife.vue')['default']
    GithubIcon: typeof import('./components/icons/GithubIcon.vue')['default']
    Graphs: typeof import('./components/playground/Graphs.vue')['default']
    Hamming: typeof import('./components/playground/HammingCode.vue')['default']
    HammingCode: typeof import('./components/playground/HammingCode.vue')['default']
    LightModeIcon: typeof import('./components/icons/LightModeIcon.vue')['default']
    MailIcon: typeof import('./components/icons/MailIcon.vue')['default']
    NetworkIcon: typeof import('./components/icons/NetworkIcon.vue')['default']
    Particle: typeof import('./components/playground/ParticleGame.vue')['default']
    ParticleGame: typeof import('./components/playground/ParticleGame.vue')['default']
    PathFinder: typeof import('./components/playground/PathFinder.vue')['default']
    PictureIcon: typeof import('./components/icons/PictureIcon.vue')['default']
    Pictures: typeof import('./components/Pictures.vue')['default']
    Playground: typeof import('./components/Playground.vue')['default']
    PlaygroundIcon: typeof import('./components/icons/PlaygroundIcon.vue')['default']
    Projects: typeof import('./components/Projects.vue')['default']
    Sorting: typeof import('./components/playground/SortingAlgo.vue')['default']
    SortingAlgo: typeof import('./components/playground/SortingAlgo.vue')['default']
    Toolbar: typeof import('./components/playground/ToolBar.vue')['default']
    ToolBar: typeof import('./components/playground/ToolBar.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}
