name: Build and Push to Docker Hub

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: someone110101/portfolio:latest

      - name: Wait to ensure DockerHub image is available
        run: sleep 5

      - name: Trigger Coolify redeploy
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.COOLIFY_HOOK_TOKEN }}" \
          ${{ secrets.COOLIFY_REDEPLOY_HOOK }}
        env:
          COOLIFY_REDEPLOY_HOOK: ${{ secrets.COOLIFY_REDEPLOY_HOOK }}
          COOLIFY_HOOK_TOKEN: ${{ secrets.COOLIFY_HOOK_TOKEN }}
